### ISSUE TITLE
Dead battery = all data lost.

### ISSUE THREAD

**Issue by BlaikM** [lightbeard/GPS-Orienteering-Logger#3]
If the phone's battery dies while the app is running, for any reason, the app dies without saving and all log data is lost.  The user can end up with nothing without warning.

**Comment by lightbeard** [comment]
So what you found is all previously recorded gpx files are lost and not just the one in progress?

**Comment by BlaikM** [comment]
I think I had previously deleted all the others, as I had already emailed
them to myself.  The issue I was reporting was that you lost all of the one
in progress.  I tried testing it up here in the mountains around Boulder
while hiking on Friday.  I turned the screen down, but couldn't turn it
down all the way bc then I couldn't see it whatsoever in the outside
light.  Hike lasted 4-5 hours, and when I took the phone out, it was dead.
When I recharged and opened the app back up, nothing from the hike was
recorded.  ☹️

Blaik
